name: Main CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4

      - name: Install chromium
        run: sudo apt install chromium-browser

      - name: Install chromium
        run: sudo apt install chromium-chromedriver

      - name: Install npm dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Install node-red
        run: sudo npm install -g --unsafe-perm node-red

      - name: Install package into node-red
        run: sudo npm install -g .

      - name: Run node-red
        run: node-red > node-red-log.txt 2>&1 &

      - name: Run chromedriver
        run: chromedriver --verbose > chromedriver-log.txt 2>&1 &

      - name: Wait on
        uses: iFaxity/wait-on-action@v1
        with:
          resource: http-get://localhost:1880

      - name: Echo log
        run: cat node-red-log.txt
